import assert from "node:assert/strict";
import test from "node:test";
import { renderChart } from "../src/render.mjs";

const history = {
  repository: "owner/repo",
  repositoryCreatedAt: "2024-03-11",
  updatedAt: "2026-09-01T03:00:00.000Z",
  observedFrom: "2026-09-01",
  points: [
    { date: "2025-01-01", count: 1, source: "backfill" },
    { date: "2025-06-01", count: 250, source: "backfill" },
    { date: "2026-09-01", count: 1234, source: "observed" },
  ],
};

test("renderChart produces an accessible standalone SVG", () => {
  const svg = renderChart(history, { width: 900, height: 600 });
  assert.match(svg, /^<\?xml/);
  assert.match(svg, /<svg[^>]+role="img"/);
  assert.match(svg, />Star History<\/text>/);
  assert.match(svg, />owner\/repo<\/text>/);
  assert.match(svg, />GitHub Stars<\/text>/);
  assert.match(svg, />Date<\/text>/);
  assert.match(svg, /data-mode="date" data-scale="linear" data-legend-position="top-left"/);
  assert.match(svg, /font-family: "GH Star Hand"/);
  assert.match(svg, /id="xkcdify"/);
  assert.match(svg, /baseFrequency="0\.05"/);
  assert.match(svg, /scale="5"/);
  assert.match(svg, /filterUnits="userSpaceOnUse" x="-5" y="-5" width="100%" height="100%"/);
  assert.match(svg, /stroke="#dd4528"/);
  assert.match(svg, /class="xaxis" transform="translate\(0,490\)"/);
  assert.match(svg, /d="M0\.5,0\.5H800\.5"/);
  assert.match(svg, /d="M-1,490\.5H0\.5V0\.5H-1"/);
  assert.match(svg, /width="109" height="36"/);
  assert.match(svg, /x="105" y="29"[^>]+font-size="18px" font-weight="600" text-anchor="end"/);
  assert.match(svg, /font-size: 17px; font-weight: 600/);
  assert.match(svg, /font-size="22px" font-weight="700"/);
  assert.match(svg, /font-size="18px" font-weight="600"[^>]*>Date<\/text>/);
  assert.match(svg, /font-size="18px" font-weight="600"[^>]*>GitHub Stars<\/text>/);
  assert.match(svg, /font-size="15px" font-weight="500"[^>]*>Generated by/);
  assert.match(svg, />Generated by GH Star History for Actions<\/text>/);
  assert.match(svg, /<metadata id="project-metadata">/);
  assert.match(svg, /https:\/\/github\.com\/kernalix7\/GH-Star-History-for-Actions/);
  assert.match(svg, /<text x="-250" y="12" dy="\.75em"/);
  assert.match(svg, /class="xkcd-chart-xyline" d="M[^\"]+C[^\"]+"/);
  assert.match(svg, />200<\/text>/);
  assert.match(svg, />1200<\/text>/);
  assert.doesNotMatch(svg, /linearGradient|daily observations begin|★/);
  assert.doesNotMatch(svg, /undefined|NaN/);
});

test("renderChart escapes custom titles", () => {
  const svg = renderChart(history, { title: "<script>alert('x')</script>", theme: "dark" });
  assert.doesNotMatch(svg, /<script>/);
  assert.match(svg, /&lt;script&gt;/);
  assert.match(svg, /#0d1117/);
  assert.match(svg, /stroke="#ff6b6b"/);
});

test("renderChart embeds a validated owner avatar beside the title", () => {
  const avatarDataUrl = "data:image/png;base64,iVBORw==";
  const svg = renderChart(history, { avatarDataUrl });
  assert.match(svg, /id="clip-circle-title"/);
  assert.match(svg, /<image x="366" y="12" width="22" height="22"/);
  assert.match(svg, /href="data:image\/png;base64,iVBORw=="/);

  const unsafe = renderChart(history, { avatarDataUrl: "https://example.com/avatar.svg" });
  assert.doesNotMatch(unsafe, /example\.com\/avatar/);
});

test("renderChart supports timeline and symlog variants", () => {
  const svg = renderChart(history, {
    mode: "timeline",
    scale: "log",
    legendPosition: "bottom-right",
  });
  assert.match(svg, /data-mode="timeline" data-scale="log" data-legend-position="bottom-right"/);
  assert.match(svg, />Timeline<\/text>/);
  assert.match(svg, /class="legend" data-position="bottom-right"/);
  assert.match(svg, /<rect x="683" y="439" width="109" height="36"/);
  assert.match(svg, />0<\/text>/);
  assert.match(svg, />10<\/text>/);
  assert.match(svg, />100<\/text>/);
  assert.match(svg, />1000<\/text>/);
  assert.match(svg, /(?:months|years)<\/text>/);
  assert.doesNotMatch(svg, /undefined|NaN/);
});

test("renderChart keeps a one-observation repository visible", () => {
  const svg = renderChart({
    ...history,
    repositoryCreatedAt: "2026-09-01",
    points: [{ date: "2026-09-01", count: 1, source: "observed" }],
  });
  assert.match(svg, /<circle class="single-point" cx="0"[^>]+r="4"/);
  assert.match(svg, /transform="translate\(0\.5,0\)"[\s\S]+>Sep 01<\/text>/);
  assert.doesNotMatch(svg, />Sep 0[2-9]<\/text>/);
  assert.doesNotMatch(svg, /undefined|NaN/);
});

test("renderChart uses integer star ticks for a zero-star repository", () => {
  const svg = renderChart({
    ...history,
    repositoryCreatedAt: "2026-09-01",
    points: [{ date: "2026-09-01", count: 0, source: "observed" }],
  });
  assert.match(svg, />0<\/text>/);
  assert.match(svg, />1<\/text>/);
  assert.doesNotMatch(svg, />0\.[0-9]+<\/text>/);
});
